baseURL = "https://sfosc.org/preview/"
languageCode = "en-us"
title = "Sustainable Free and Open Source Communities"
theme = "hugo-theme-learn"

[params]
author = "The Sustainable Free and Open Source Community"
description = "Guidelines for building sustainable free and open source communities"
disableBreadcrumb = false
themeVariant = "sfosc"
editURL = "https://github.com/sfosc/sfosc/edit/master/content/"
isPreview = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
