version: 2.1
workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.55
    steps:
      - checkout
      - run:
          name: Clone pages repo
          command: git clone --depth 1 https://github.com/Beanow/sfosc-pages.git public
      - run:
          name: Hugo build
          command: HUGO_ENV=production hugo
      # - run:
      #     name: "Test Website"
      #     command: htmlproofer ./public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - persist_to_workspace:
          root: public
          paths:
            - '.'
  deploy:
    docker:
      - image: cibuilds/base
    steps:
      - attach_workspace:
          at: public
      - add_ssh_keys:
          fingerprints:
            - 9f:74:57:dc:23:64:c1:e9:0f:2c:f5:7f:c9:32:59:55
      - run:
          name: Commit and push
          command: |
            cd public
            git config credential.helper 'cache --timeout=30'
            # This allows pushing without knowing github's key fingerprint ahead of time.
            git config core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
            git config user.email "bot@sfosc.org"
            git config user.name "Deployment Bot"
            git add --all
            git commit -m "Rebuilding site `date`"
            git push git@github.com:Beanow/sfosc-pages.git master
